name: Deploy
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Deploy
            - run: rsync -e "ssh -p 22 -i $HOME/.ssh/ssh_key -o StrictHostKeyChecking=no" --archive --compress --delete . root@194-67-108-154.cloudvps.regruhosting.ru:/var/www/adv-teuvazheva.ru/html
